#!/bin/bash

# Funkcja dodająca grupę
add_group() {
    read -p "Podaj nazwę grupy: " group_name
    sudo groupadd $group_name
    echo "Grupa $group_name została utworzona."
}

# Funkcja dodająca użytkownika
add_user() {
    read -p "Podaj nazwę użytkownika: " username
    sudo useradd $username
    echo "Użytkownik $username został utworzony."
}

# Funkcja dodająca wielu użytkowników
add_multiple_users() {
    read -p "Podaj nazwę bazową użytkowników: " base_name
    read -p "Podaj liczbę użytkowników do utworzenia: " count

    for ((i=1; i<=count; i++)); do
        username="${base_name}${i}"
        sudo useradd $username
        echo "Użytkownik $username został utworzony."
    done
}

# Funkcja przypisująca użytkownika do grupy
add_user_to_group() {
    read -p "Podaj nazwę użytkownika: " username
    read -p "Podaj nazwę grupy: " group_name
    sudo usermod -a -G $group_name $username
    echo "Użytkownik $username został przypisany do grupy $group_name."
}

# Funkcja przypisująca użytkownika do wielu grup
add_user_to_multiple_groups() {
    read -p "Podaj nazwę użytkownika: " username
    read -p "Podaj listę grup oddzieloną spacją: " groups
    IFS=' ' read -r -a groups_array <<< "$groups"

    for group in "${groups_array[@]}"; do
        sudo usermod -a -G $group $username
        echo "Użytkownik $username został przypisany do grupy $group."
    done
}

# Funkcja tworząca nową grupę i przypisująca użytkownika
add_user_to_new_group() {
    read -p "Podaj nazwę użytkownika: " username
    read -p "Podaj nazwę nowej grupy: " new_group
    sudo groupadd $new_group
    sudo usermod -a -G $new_group $username
    echo "Grupa $new_group została utworzona, a użytkownik $username został do niej przypisany."
}

# Główna pętla menu
while true; do
    echo "1. Dodaj grupę"
    echo "2. Dodaj użytkownika"
    echo "3. Dodaj wielu użytkowników"
    echo "4. Dodaj użytkownika do grupy"
    echo "5. Dodaj użytkownika do wielu grup"
    echo "6. Dodaj użytkownika do nowej grupy"
    echo "7. Wyjdź"

    read -p "Wybierz opcję: " option

    case $option in
        1)
            add_group
            ;;
        2)
            add_user
            ;;
        3)
            add_multiple_users
            ;;
        4)
            add_user_to_group
            ;;
        5)
            add_user_to_multiple_groups
            ;;
        6)
            add_user_to_new_group
            ;;
        7)
            break
            ;;
        *)
            echo "Nieprawidłowa opcja."
            ;;
    esac

    echo
done
