#!/bin/bash

# Funkcja dodająca grupę
add_group() {
    read -p "Podaj nazwę grupy: " group_name
    sudo groupadd $group_name
    echo "Grupa $group_name została utworzona."
}

# Funkcja dodająca użytkownika
add_user() {
    read -p "Podaj nazwę użytkownika: " username
    sudo useradd $username
    echo "Użytkownik $username został utworzony."
}

# Funkcja zmieniająca hasło użytkownika
change_user_password() {
    read -p "Podaj nazwę użytkownika: " username
    sudo passwd $username
    echo "Hasło użytkownika $username zostało zmienione."
}

# Funkcja tworząca przykładowy profil użytkownika
create_sample_profile() {
    read -p "Podaj nazwę użytkownika: " username

    profile_file="/home/$username/.bashrc"

    echo "# Przykładowy profil" >> $profile_file
    echo "export MY_VARIABLE='Hello, World!'" >> $profile_file

    echo "Przykładowy profil został utworzony dla użytkownika $username."
}

# Główna pętla menu
while true; do
    echo "1. Dodaj grupę"
    echo "2. Dodaj użytkownika"
    echo "3. Zmień hasło użytkownika"
    echo "4. Utwórz przykładowy profil użytkownika"
    echo "5. Wyjdź"

    read -p "Wybierz opcję: " option

    case $option in
        1)
            add_group
            ;;
        2)
            add_user
            ;;
        3)
            change_user_password
            ;;
        4)
            create_sample_profile
            ;;
        5)
            break
            ;;
        *)
            echo "Nieprawidłowa opcja."
            ;;
    esac

    echo
done
