#!/bin/bash

# Funkcja dodająca grupę
add_group() {
    read -p "Podaj nazwę grupy: " group_name
    sudo groupadd $group_name
    echo "Grupa $group_name została utworzona."
}

# Funkcja dodająca użytkownika
add_user() {
    read -p "Podaj nazwę użytkownika: " username
    sudo useradd $username
    echo "Użytkownik $username został utworzony."
}

# Funkcja dodająca wielu użytkowników
add_multiple_users() {
    read -p "Podaj nazwę bazową użytkowników: " base_name
    read -p "Podaj liczbę użytkowników do utworzenia: " count

    for ((i=1; i<=count; i++)); do
        username="${base_name}${i}"
        sudo useradd $username
        echo "Użytkownik $username został utworzony."
    done
}

# Funkcja przypisująca użytkownika do grupy
add_user_to_group() {
    read -p "Podaj nazwę użytkownika: " username
    read -p "Podaj nazwę grupy: " group_name
    sudo usermod -a -G $group_name $username
    echo "Użytkownik $username został przypisany do grupy $group_name."
}

# Główna pętla menu
while true; do
    echo "1. Dodaj grupę"
    echo "2. Dodaj użytkownika"
    echo "3. Dodaj wielu użytkowników"
    echo "4. Dodaj użytkownika do grupy"
    echo "5. Wyjdź"

    read -p "Wybierz opcję: " option

    case $option in
        1)
            add_group
            ;;
        2)
            add_user
            ;;
        3)
            add_multiple_users
            ;;
        4)
            add_user_to_group();;
        5)
            ;;
   esac
esac
